### ISSUE TITLE
协议貌似已更改？

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/QQRobot#10]

**Comment by zeruniverse** [comment]
Ref: https://github.com/zeruniverse/QQParking/issues/14

**Comment by hexsum** [comment]
我这边仍然可以正常登录（不是使用该项目代码），协议应该没有更新

**Comment by zeruniverse** [comment]
能发出消息吗？ 貌似是有这个问题： https://github.com/Yinzo/SmartQQBot/issues/32

**Comment by hexsum** [comment]
哦哦 你贴出来的这个链接，是很久之前更新的 ，这短时间没有其它更新了

**Comment by zeruniverse** [comment]
你能发消息么？登陆我已经修好了，VFWEBQQ也对了，但是现在发消息会100001错误

**Comment by hexsum** [comment]
我的用了很长时间了，可以发消息，不过官方最近把发送群临时小窗消息功能给屏蔽了 其它发消息正常 我有空也看下你这个项目代码

发自 网易邮箱大师
在2016年01月26日 11:12，Jeffery Zhao 写道:

你能发消息么？登陆我已经修好了，VFWEBQQ也对了，但是现在发消息会100001错误

**Comment by zeruniverse** [comment]
你直接看这个项目的MASTER呗，我现在这份代码应该是可以登陆并接受消息的，但是私聊发消息返回retcode 100001

**Comment by zeruniverse** [comment]
很奇怪的问题 貌似要按照webqq的顺序把每个api都访问一遍 不然发不出消息

**Comment by zeruniverse** [comment]
SOLVED
