### ISSUE TITLE
获取真实群号

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/QQRobot#11]
按目前的情况看新版webqq已无法获取真实群号，只能靠群名进行人机交互了。。。

**Comment by hexsum** [comment]
有一个接口可以获取到群号，但不是来自webqq，可能来自pc端或手机端，我明天找一下，还有就是qun.qq.com这个页面的群管理功能也可以获取到群号，而且webqq的登录cookie是可以直接共享给这个页面的，登录都省了

**Comment by zeruniverse** [comment]
谢了，暂时能用群名解决，先不折腾了。
