### ISSUE TITLE
现在smart qq还能用吗

### ISSUE THREAD

**Issue by woolen-sheep** [zeruniverse/QQRobot#12]
下载3.6版本运行各种报错。登录smart qq用小号给自己发消息也看不到，连群也没有，抓包没有发现有心跳包。它还健在吗。

**Comment by zeruniverse** [comment]
至少我能用。你先登录下电脑版再挂程序试试。注意3.6要用群名不是群号

**Comment by woolen-sheep** [comment]
在github的另一个qq robot项目下面看到有人出现了同样的问题，解决方法为，用chrome去w.qq.com登陆一次。chrome登录的smartqq一切正常，firefox登录就乱了，比如抓包retcode会返回10003。
