### ISSUE TITLE
你好，怎么研究 Android QQ 协议呢？

### ISSUE THREAD

**Issue by zhangnew** [zeruniverse/QQRobot#13]
也是抓包分析吗？

网上一些付费QQ机器人貌似都是用的手机QQ协议，包括晨风，QQPlus，酷Q等。

**Comment by zeruniverse** [comment]
1. 装安卓模拟器，下载qq，使用wireshark抓包

上面这种方法是最容易的，也有别的选项
2. 逆向手机QQ
3. 进入TX或找一个TX上班的人，拿到对应部分代码

**Comment by zhangnew** [comment]
谢谢，还是抓包吧。我还不想坐牢。

**Comment by zeruniverse** [comment]
明明都是合法的……

**Comment by zhangnew** [comment]
逆向合法吗。。

**Comment by zeruniverse** [comment]
下载下来逆向就好了呀，难道你要告诉TX说我把你的qq软件逆向了？你别说没人知道吧

**Comment by zhangnew** [comment]
0.0

有个群打算现在学习手机和PC协议，不知道你完成了多少了，群主打算年后建立一个单独的讨论网站

**Comment by zeruniverse** [comment]
我最近没空搞这个……Paper还没动……

**Comment by zhangnew** [comment]
好吧。我也没时间。。
