### ISSUE TITLE
"errmsg":"","retcode":103

### ISSUE THREAD

**Issue by james0479** [zeruniverse/QQRobot#16]
一直在返回103，请问是什么原因
QQBot.py[line:447] INFO Check html: {"errmsg":"","retcode":103}

**Comment by zeruniverse** [comment]
用你的浏览器登录一遍webqq，然后再重试。这个类似于账号被保护

**Comment by james0479** [comment]
非常感谢，已经解决
测试了几天都比较正常，但这2天总是出现”群有动态，但是没有被监控“,小号已经加入到群中，看日志也已经提示关注，请问是什么问题，谢谢

**Comment by zeruniverse** [comment]
退出重新登录……获取时的群id和真实uin不同。这个比较诡异，有的时候会出现。解决方案未知

**Comment by james0479** [comment]
退出重新登录后恢复正常，多谢
