### ISSUE TITLE
这个怎么把整个项目封装成接口去调用呢

### ISSUE THREAD

**Issue by OutstandingJin** [zeruniverse/QQRobot#17]
比如，我想给QQ群推送一些消息，分享一些音乐什么的。

**Comment by OutstandingJin** [comment]
现在明白了

**Comment by zeruniverse** [comment]
I don't have plan to implement those specific stuff. There's no such interface, you have to read the code and develop it yourself. Or there might be a better choice for you if you want something complicated: https://github.com/Yinzo/SmartQQBot
