### ISSUE TITLE
向服务器查询新消息时，有几率会出现 {"errmsg":"","retcode":103}

### ISSUE THREAD

**Issue by piterjoin** [zeruniverse/QQRobot#18]
登录成功后，循环  向服务器查询新消息 出现 {"errmsg":"","retcode":103}，而不是正常的{"errmsg":"","retcode":0}
查询群成员信息或则查询数据的都是正常的，接收新信息没用（手机显示有群消息，也有临时消息）

同时打开w.qq.com的情况下，程序就能收到信息

**Comment by zeruniverse** [comment]
Duplicated to #16
