### ISSUE TITLE
QQ安全中心登陆挂了

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/QQRobot#20]
安全中心已无法登陆webqq，即使在chrome上也不行。

**Comment by wujunze** [comment]
现在这个QQ机器人还能用不?

**Comment by zeruniverse** [comment]
国外的ip挂了。测了一下发现我连webqq都登陆不了。

安全中心登录挂了。只能用手机qq扫码。

国内能不能用不知道 你可以试一下 感觉TX准备放弃webqq了，不能用是早晚的事情。

**Comment by wujunze** [comment]
咱们可以分析一下手机QQ的协议    最近我有兴趣整一下QQ机器人

**Comment by zeruniverse** [comment]
抓过iphone的包 都是加密的……没有安卓机……
