### ISSUE TITLE
一个电脑上可以多开吗？

### ISSUE THREAD

**Issue by zhzblackc** [zeruniverse/QQRobot#22]
一个电脑上可以多开吗？理论上如果可以多开，就能实现几个机器人按指定的文本相互聊天对吗？

**Comment by zeruniverse** [comment]
是 最后两个号会不断聊，然后被踢下线。不过这个版本是每30条信息忽略一条的，就是防止这种死循环

**Comment by zhzblackc** [comment]
能不能做到多个号，还有就是文本读完了不重新读，就不用循环了。

**Comment by zeruniverse** [comment]
额，不是很理解你在问什么。。。一个程序开多个号做不到

**Comment by zhzblackc** [comment]
就是几个机器人互聊，分别按自己的文本，你上面说会循环，我的意思是让他们把自己的文本聊完了，就不聊了，这样可以做到吗？相当于是营造群活跃的假象。

**Comment by zeruniverse** [comment]
这个你要自己改代码

**Comment by zhzblackc** [comment]
能指导下吗？

**Comment by zeruniverse** [comment]
这个指导不了，，，抱歉
