### ISSUE TITLE
v.png 出不来 = =、

### ISSUE THREAD

**Issue by Senn666** [zeruniverse/QQRobot#23]
按照步骤做的，但是就是不出来v.png？？？

**Comment by Arven2015** [comment]
你查看日志文件了吗

**Comment by Jinming-Su** [comment]
这个问题我也遇到了，你应该先touch一个v.png，之后运行自动覆盖掉就好了 @Senn666

**Comment by zeruniverse** [comment]
？实现的时候没有touch这个设定。请检查log，如果log没问题请检查程序是否有权限写文件。

**Comment by viphsx123** [comment]
我也有这个问题，死活生成不出来png  ，写权限肯定有的

**Comment by zeruniverse** [comment]
请提供log。生成不了png的原因有很多，不提供log没法debug

**Comment by viphsx123** [comment]
@zeruniverse   qbot.log文件是空的，0字节

**Comment by viphsx123** [comment]
执行sudo nohup python2 QQBot.py >qbot.log& 之后，只在终端上出现了这个 ：[1] 7653  ，目录下并没有v.png

**Comment by Arven2015** [comment]
我的已经可已扫描二维码登录了，手机qq也会有登录成功的提示，但后面还是有些问题。

**Comment by viphsx123** [comment]
@Arven2015  你的v.png弄出来了 ？

**Comment by Arven2015** [comment]
@viphsx123 出来了，不过我是在window平台  python3.5

**Comment by viphsx123** [comment]
@Arven2015  我mac下 2.7 不知道是不是环境问题

**Comment by Arven2015** [comment]
@viphsx123 这个代码原本是2.x的，应该更容易才对。

**Comment by viphsx123** [comment]
@Arven2015  嗯，我也登录成功了，但是还有一些问题
Mon, 24 Oct 2016 17:01:56  QQBot.py[line:448] INFO Check html: {"errmsg":"error!!!","retcode":103}

Mon, 24 Oct 2016 17:01:56  QQBot.py[line:448] INFO Check html: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by zeruniverse** [comment]
502 bad gateway是腾讯的问题，没法解决。你试试直接浏览器能不能登陆。如果获取不了v.png先用浏览器登陆一遍试试

**Comment by zeruniverse** [comment]
问题解决了没？

**Comment by zeruniverse** [comment]
Closed due to no response
