### ISSUE TITLE
请注意python版本和smartqq html的变动

### ISSUE THREAD

**Issue by Arven2015** [zeruniverse/QQRobot#24]
我使用python3.5，改动了几处语法变动，然后是webqq html页面的变动，但是在三次尝试登录的地方最终还是失败了。

**Comment by zeruniverse** [comment]
好像现在只能用手机QQ扫描登陆了

感觉TX要放弃SmartQQ了。这个东西我自己已经一段时间没在用了，所以不是很清楚TX哪里又改协议了

**Comment by zeruniverse** [comment]
@Arven2015 问题解决了吗？

**Comment by Arven2015** [comment]
没有，我初次接触这方面，扫描二维码后的登录网址是hard code，请问当初你是从哪里分析的呢？ @zeruniverse

**Comment by zeruniverse** [comment]
抓包的，也有可能现在地址改了

**Comment by zeruniverse** [comment]
Closed due to no response
