### ISSUE TITLE
群聊一直处于JSON无法解码的状态，私聊正常

### ISSUE THREAD

**Issue by Jinming-Su** [zeruniverse/QQRobot#25]
只是怎么回事呢？我在本地的时候群聊也是可以用的，到了服务器上群聊就不能用了

**Comment by zeruniverse** [comment]
服务器的ip容易被封，我的DO服务器ip彻底被tx封了。如果私聊可以用应该ip没被封。可能怀疑异地登陆，暂时不给你发群聊

**Comment by Arven2015** [comment]
可以分享下你扫描二维码后的登录代码吗？

**Comment by zeruniverse** [comment]
@su526664687 解决了没有？

**Comment by zeruniverse** [comment]
Closed due to no response
