### ISSUE TITLE
登录成功，在群里回复!about 指令　没有反应

### ISSUE THREAD

**Issue by wujunze** [zeruniverse/QQRobot#29]
从log.log中看，已经登录成功了，但是回复!about指令没有反应，帮忙看看是怎么回事

**Comment by zeruniverse** [comment]
从readme引用：
`已知QQ会临时封禁机器人的临时对话回复和群回复，原理未知，每次封禁约为10分钟。表现为发送消息返回值retcode 为 0 但其他人无法看到。长时间挂机会导致QQ被冻结错误，QQ安全中心提示发布不良信息`   

你可以试下其他命令 比如　!follow me [请注意, !是英文的'!']

如果不行请贴出你的log.log

**Comment by zeruniverse** [comment]
抱歉，前几天放假，回复较晚

**Comment by hjm8688098** [comment]
你群聊命令没反应问题解决了吗

**Comment by zeruniverse** [comment]
20天没有回复，默认问题已解决，如果还有问题请reopen issue
