### ISSUE TITLE
登录成功后　　这个错误码是什么意思？

### ISSUE THREAD

**Issue by wujunze** [zeruniverse/QQRobot#30]
23:17:59  QQBot.py[line:743] CRITICAL retcode error when getting group list: retcode=13
登录成功后显示这个错误码，试了几次都是这个错误码
016 23:17:58  QQBot.py[line:361] INFO Login success
Tue, 20 Dec 2016 23:17:58  QQBot.py[line:362] CRITICAL 登陆二维码用时5.736秒
Tue, 20 Dec 2016 23:17:59  QQBot.py[line:743] CRITICAL retcode error when getting group list: retcode=13

**Comment by zeruniverse** [comment]
群记录错了。

Python 文件同文件夹下必须有个文件 `groupfollow.txt`, 这个文件里面必须要是**群名**, 用回车分隔。

请参考 [这里](https://github.com/zeruniverse/QQRobot/blob/master/groupfollow.txt)

**Comment by zeruniverse** [comment]
抱歉，前几天放假，回复较晚

**Comment by wujunze** [comment]
收到   我今天有空了 再试一下   谢谢
