### ISSUE TITLE
retcode 103错误

### ISSUE THREAD

**Issue by yunhungo** [zeruniverse/QQRobot#31]
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:278] CRITICAL 正在获取登陆页面
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:282] CRITICAL 正在获取appid
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:284] CRITICAL 正在获取login_sig
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:286] INFO get sign : 
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:287] CRITICAL 正在获取pt_version
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:289] INFO get g_pt_version : 10187
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:290] CRITICAL 正在获取mibao_css
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:292] INFO get g_mibao_css : 
Thu, 22 Dec 2016 03:33:40  QQBot.py[line:300] INFO [1] Get QRCode Picture Success.
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:313] INFO ['ptuiCB(', '0', ',', '0', ',', 'http://ptlogin4.web2.qq.com/check_sig?pttype=1&uin=949417747&service=ptqrlogin&nodirect=0&ptsigx=858faebe7a504ee45f1da35dae67c678879eb614a33f2b10294c5e4ef006a2330edb1ebd9f7dad962f4635ba9df4a322a8b526e488ebe94b7b02b8c95a4941af&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&f_url=&ptlang=2052&ptredirect=100&aid=501004106&daid=164&j_later=0&low_login_hour=0&regmaster=0&pt_login_type=3&pt_aid=0&pt_aaid=16&pt_light=0&pt_3rd_aid=0', ',', '0', ',', '\xe7\x99\xbb\xe5\xbd\x95\xe6\x88\x90\xe5\x8a\x9f\xef\xbc\x81', ', ', '\xe5\xb0\x8f\xe8\x90\x8c\xe5\xa7\xac', ');\r\n']
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:317] CRITICAL 二维码已扫描，正在登陆
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:91] ERROR Get mibao_res Url Error.
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:335] INFO PTWebQQ: 00d68b15cb52565098d73c7112f70b4f38801ea8533949caeb8757c4c2f9c024
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:345] INFO getvfwebqq html:  {"retcode":0,"result":{"vfwebqq":"f7e598816ec2d713ed65b1f65e4e4422720b7fc61784960bda345fedf10b4b8a58ea207263b56bc1"}}
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:359] CRITICAL QQ号：123456789 登陆成功, 用户名：小萌姬
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:360] INFO Login success
Thu, 22 Dec 2016 03:33:57  QQBot.py[line:361] CRITICAL 登陆二维码用时0.864秒
Thu, 22 Dec 2016 03:33:58  QQBot.py[line:753] INFO 关注:【TSZ辅助】交流分群2.
Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:447] INFO Check html: {"errmsg":"error!!!","retcode":103}

Thu, 22 Dec 2016 03:33:58  QQBot.py[line:439] CRITICAL 轮询错误超过五次

**Comment by turinglambdaai** [comment]
我也遇到这问题了，请问你现在解决了吗？

**Comment by zeruniverse** [comment]
103错误没有办法。这是腾讯的问题。请尝试：
+ 换电脑 （IP）  
+ 先浏览器正常登陆smartqq，再用挂机PYTHON
+ 用Q龄较长的QQ

**Comment by zeruniverse** [comment]
抱歉，前几天放假，回复较晚
