### ISSUE TITLE
群消息没反应

### ISSUE THREAD

**Issue by hjm8688098** [zeruniverse/QQRobot#32]
群里使用!ai等命令没反应，是英文!  什么原因呢

**Comment by zeruniverse** [comment]
检查log.log，看看那条消息有没有被记录

**Comment by hjm8688098** [comment]
看过，显示群被监控，但没被触发

**Comment by zeruniverse** [comment]
如果工作正常，!ai ...那句话会记录在log里，你看看有没有

**Comment by hjm8688098** [comment]
没有被记录

**Comment by hjm8688098** [comment]
单人对聊正常

**Comment by zeruniverse** [comment]
把log贴上来

**Comment by hjm8688098** [comment]
咋没发贴图

**Comment by hjm8688098** [comment]
发你邮箱zzy8200@gmail.com

**Comment by zeruniverse** [comment]
你把log用记事本打开 里面的内容复制下来 粘贴过来。

**Comment by hjm8688098** [comment]
Thu, 05 Jan 2017 02:09:56  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"group_message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"!ai 你是谁？"],"from_uin":1074076706,"group_code":1074076706,"msg_id":9454,"msg_type":0,"send_uin":1272066522,"time":1483553471,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 02:09:56  QQBot.py[line:196] INFO 1074076706群有动态，但是没有被监控
Thu, 05 Jan 2017 02:10:30  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"group_message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"ai! 你是谁？"],"from_uin":4027627447,"group_code":4027627447,"msg_id":21134,"msg_type":0,"send_uin":1272066522,"time":1483553504,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 02:10:30  QQBot.py[line:196] INFO 4027627447群有动态，但是没有被监控
Thu, 05 Jan 2017 02:10:41  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"在么"],"from_uin":1272066522,"msg_id":1610,"msg_type":0,"time":1483553516,"to_uin":3237695534}}],"retcode":0}

**Comment by hjm8688098** [comment]
还有个问题，我询问早餐菜谱，日志显示有，但扣扣没显示
##日志内容##
}

Thu, 05 Jan 2017 07:14:12  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507}
Thu, 05 Jan 2017 07:14:12  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507}
Thu, 05 Jan 2017 07:14:12  QQBot.py[line:475] INFO 私聊线程生成，私聊对象：2801037507
Thu, 05 Jan 2017 07:14:12  QQBot.py[line:499] INFO PM get info from AI: 吃早饭
Thu, 05 Jan 2017 07:14:12  QQBot.py[line:502] INFO AI REPLY:{"code":308000,"text":"亲，已帮您找到菜谱信息","list":[{"name":"制定一周早餐","icon":"","info":"耐心","detailurl":"http://m.xiachufang.com/recipe/100531217/?ref=tuling"},{"name":"一周不重复早餐","icon":"","info":"爱心、其实有四十天不重复，一一、上传好累哟","detailurl":"http://m.xiachufang.com/recipe/100585316/?ref=tuling"},{"name":"早餐卷","icon":"","info":"低筋面粉、盐、开水、冷水、全麦卷饼、土豆、胡萝卜、海带丝、豆腐衣、鸡蛋、海天金标生抽、招牌拌饭酱、芝麻油、葱花","detailurl":"http://m.xiachufang.com/recipe/268278/?ref=tuling"},{"name":"给女儿做的一周早饭专辑","icon":"","info":"早饭","detailurl":"http://m.xiachufang.com/recipe/100443609/?ref=tuling"},{"name":"土豆火腿早餐饼","icon":"","info":"土豆、香肠、胡萝卜、小香芹、面粉、盐","detailurl":"http://m.xiachufang.com/recipe/267812/?ref=tuling"},{"name":"早餐来一锅香脆的生煎饺子","icon":"","info":"中粉、猪肉泥、芹菜、香菇、盐、小葱、胡椒粉、鸡蛋、鸡精、小麦淀粉","detailurl":"http://m.xiachufang.com/recipe/100596116/?ref=tuling"},{"name":"葱油拌面——5分钟早餐","icon":"","info":"挂面、酱油、糖、葱花、油","detailurl":"http://m.xiachufang.com/recipe/100517726/?ref=tuling"},{"name":"鸡蛋灌饼：街头早点自己做","icon":"","info":"面粉、鸡蛋、盐、小葱、香油","detailurl":"http://m.xiachufang.com/recipe/100294830/?ref=tuling"},{"name":"鸡蛋仔（超级快捷早餐）","icon":"","info":"鸡蛋仔预拌粉、鸡蛋、牛奶、黄油","detailurl":"http://m.xiachufang.com/recipe/100626118/?ref=tuling"},{"name":"开胃早餐面","icon":"","info":"可以是湿面条，也可以是挂面、鸡蛋、小油菜、海苔或紫菜、火腿、葱姜末","detailurl":"http://m.xiachufang.com/recipe/100426420/?ref=tuling"},{"name":"【健康减脂早餐】无油香蕉松饼（超简单）","icon":"","info":"香蕉（越熟越好）、鸡蛋、牛奶、面粉","detailurl":"http://m.xiachufang.com/recipe/100493949/?ref=tuling"},{"name":"快手葱油小饼（早餐饼）","icon":"","info":"普通面粉、鸡蛋、盐、葱、食用油、芝麻油","detailurl":"http://m.xiachufang.com/recipe/100157195/?ref=tuling"},{"name":"【早餐土豆鸡蛋饼】","icon":"","info":"土豆、鸡蛋、胡萝卜、青椒","detailurl":"http://m.xiachufang.com/recipe/100557676/?ref=tuling"},{"name":"玉米饼（分分钟搞定简单早餐）","icon":"","info":"玉米粉、普通面粉、牛奶、白糖、鸡蛋液","detailurl":"http://m.xiachufang.com/recipe/100452506/?ref=tuling"},{"name":"披萨蛋（快速早餐）","icon":"","info":"鸡蛋、培根、红辣椒、青辣椒
####qq内容###
亲，已帮您找到菜谱信息
##
就这一句完了

**Comment by hjm8688098** [comment]
新闻查询也是，日志有内容，但扣扣没发出来
Thu, 05 Jan 2017 08:40:14  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"今天早上的新闻"],"from_uin":1272066522,"msg_id":2857,"msg_type":0,"time":1483576890,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 08:40:14  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507, 1948660806: 2049214498}
Thu, 05 Jan 2017 08:40:14  QQBot.py[line:499] INFO PM get info from AI: 今天早上的新闻
Thu, 05 Jan 2017 08:40:15  QQBot.py[line:502] INFO AI REPLY:{"code":302000,"text":"亲，已帮您找到相关新闻","list":[{"article":"减肥早上吃什么早餐好?健康食谱帮你燃脂","source":"新浪新闻","icon":"http://p5.qhmsg.com/dmfd/120_90_/t01e487b5e920c014db.jpg?size=600x450","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=0&m=ff14eb3173f3a3689ceb9bbaa035235efcf5f500&u=http%3A%2F%2Fnews.xinhuanet.com%2Ffood%2F2017-01%2F05%2Fc_1120234634.htm&sign=news_mso&refer=list"},{"article":"大河\"新年第一骑\"要来了 周六清晨,咱们一起出发!","source":"新浪新闻","icon":"http://p0.qhmsg.com/dmfd/120_90_/t01d228dc785310c888.jpg?size=620x349","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=1&m=42a36865d01da38e33e23b9b9242c364a7db1a7d&u=http%3A%2F%2Fnews.k618.cn%2Fsociety%2F201701%2Ft20170105_9964595.html&sign=news_mso&refer=list"},{"article":"清晨火灾一死多伤 安全警钟再次敲响","source":"新浪新闻","icon":"http://p6.qhmsg.com/dmfd/120_90_/t01b1e22f731d9404bc.jpg?size=720x576","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=video_0&m=220ca23dd38fa937514867518218d5a91435014d&u=http%3A%2F%2Fvideo.btime.com%2Fnews%2F20170104%2Fv1761354.shtml&sign=news_mso&refer=list"},{"article":"长沙:今天早上8:30 长沙直达昆明首趟高铁开出","source":"新浪新闻","icon":"http://p3.qhmsg.com/dmfd/120_90_/t01068eb5604a35a4a1.jpg?size=720x576","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=video_1&m=bd5afb890666e9350b41e7086beae54d9667846e&u=http%3A%2F%2Fvideo.btime.com%2Fnews%2F20161228%2Fv1729999.shtml&sign=news_mso&refer=list"},{"article":"清晨火灾一死多伤 安全警钟再次敲响","source":"新浪新闻","icon":"http://p6.qhmsg.com/dmfd/120_90_/t01b1e22f731d9404bc.jpg?size=720x576","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=panel_video_0&m=220ca23dd38fa937514867518218d5a91435014d&u=http%3A%2F%2Fvideo.btime.com%2Fnews%2F20170104%2Fv1761354.shtml&sign=news_mso&refer=list"},{"article":"长沙:今天早上8:30 长沙直达昆明首趟高铁开出","source":"新浪新闻","icon":"http://p3.qhmsg.com/dmfd/120_90_/t01068eb5604a35a4a1.jpg?size=720x576","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=panel_video_1&m=bd5afb890666e9350b41e7086beae54d9667846e&u=http%3A%2F%2Fvideo.btime.com%2Fnews%2F20161228%2Fv1729999.shtml&sign=news_mso&refer=list"},{"article":"现场直击:严冬清晨的巴黎难民收容中心","source":"新浪新闻","icon":"http://p0.qhmsg.com/dmfd/120_90_/t01915cd08cc80c0daf.jpg?size=720x576","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=panel_video_2&m=eb687201d1405db579cd9065e132cfdeb84e8dec&u=http%3A%2F%2Fvideo.btime.com%2Fnews%2F20161223%2Fv1707586.shtml&sign=news_mso&refer=list"},{"article":"耿晓峰清晨飞赴秦皇岛 看星座显其特点与性格?","source":"新浪新闻","icon":"","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=3&m=a8513b7192c28faa9f948e2dc50b77026eaa3446&u=http%3A%2F%2Fsports.sohu.com%2F20170104%2Fn477794644.shtml&sign=news_mso&refer=list"},{"article":"北京南苑机场受雾霾影响上午无飞机起降","source":"新浪新闻","icon":"http://p7.qhmsg.com/dmfd/120_90_/t0164b54354917e9186.jpg?size=400x254","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E6%97%A9%E4%B8%8A&pn=1&pos=7&m=8510d0115d22436900b3c87339e312067e0b0bb7&u=http%3A%2F%2Fnews.k618.cn%2Fsociety%2F201701%2Ft20170104_9960204.html&sign=news_mso&refer=list"}]}
Thu, 05 Jan 2017 08:40:15  QQBot.py[line:486] INFO Reply to 2801037507:亲，已帮您找到相关新闻
Thu, 05 Jan 2017 08:40:20  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"我要看"],"from_uin":1272066522,"msg_id":2858,"msg_type":0,"time":1483576895,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 08:40:20  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507, 1948660806: 2049214498}
Thu, 05 Jan 2017 08:40:20  QQBot.py[line:499] INFO PM get info from AI: 我要看
Thu, 05 Jan 2017 08:40:20  QQBot.py[line:502] INFO AI REPLY:{"code":100000,"text":"我也想看呢"}
Thu, 05 Jan 2017 08:40:20  QQBot.py[line:486] INFO Reply to 2801037507:我也想看呢
Thu, 05 Jan 2017 08:40:28  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"我要看新闻"],"from_uin":1272066522,"msg_id":2859,"msg_type":0,"time":1483576904,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 08:40:28  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507, 1948660806: 2049214498}
Thu, 05 Jan 2017 08:40:28  QQBot.py[line:499] INFO PM get info from AI: 我要看新闻
Thu, 05 Jan 2017 08:40:29  QQBot.py[line:502] INFO AI REPLY:{"code":200000,"text":"亲，已帮你找到新闻信息","url":"http://m.toutiao.com/#channel="}
Thu, 05 Jan 2017 08:40:29  QQBot.py[line:486] INFO Reply to 2801037507:亲，已帮你找到新闻信息
Thu, 05 Jan 2017 08:40:34  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"发给我"],"from_uin":1272066522,"msg_id":2860,"msg_type":0,"time":1483576910,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 08:40:34  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507, 1948660806: 2049214498}
Thu, 05 Jan 2017 08:40:34  QQBot.py[line:499] INFO PM get info from AI: 发给我
Thu, 05 Jan 2017 08:40:34  QQBot.py[line:502] INFO AI REPLY:{"code":100000,"text":"想要什么，只要我有我就给你哇"}
Thu, 05 Jan 2017 08:40:34  QQBot.py[line:486] INFO Reply to 2801037507:想要什么，只要我有我就给你哇
Thu, 05 Jan 2017 08:40:43  QQBot.py[line:448] INFO Check html: {"result":[{"poll_type":"message","value":{"content":[["font",{"color":"000000","name":"微软雅黑","size":10,"style":[0,0,0]}],"新闻资讯"],"from_uin":1272066522,"msg_id":2861,"msg_type":0,"time":1483576919,"to_uin":3237695534}}],"retcode":0}

Thu, 05 Jan 2017 08:40:43  QQBot.py[line:121] INFO Now FriendList:{1272066522: 2801037507, 1948660806: 2049214498}
Thu, 05 Jan 2017 08:40:43  QQBot.py[line:499] INFO PM get info from AI: 新闻资讯
Thu, 05 Jan 2017 08:40:44  QQBot.py[line:502] INFO AI REPLY:{"code":302000,"text":"亲，已帮您找到相关新闻","list":[{"article":"【MLB资讯】1月4日 有新闻尽在乐视体育","source":"新浪新闻","icon":"","detailurl":"http://m.news.so.com//transcode?ofmt=html&src=srp&q=%E8%B5%84%E8%AE

**Comment by zeruniverse** [comment]
这个没问题

1. 菜谱和新闻不支持的。
2. 你的群名输的不对，请复制粘贴不要在末尾多空格。分隔用回车
