### ISSUE TITLE
查看了群聊无反应代码原因

### ISSUE THREAD

**Issue by hjm8688098** [zeruniverse/QQRobot#33]
你好。QQRobot还是群聊问题没有反应，群名输入按要求格式的，然后我输出了第185行的判断句，发现str(gid)是代表群号，但是GroupWatchList组里面不是存的群号，就不会出现匹配情况，是不是这儿有问题

**Comment by zeruniverse** [comment]
Please refer to LN 753. GroupWatchList is exactly the list of all group ids. The Python script first reads all group names and append the **gid** of the group in `groupfollow.txt` to GroupWatchList.

**Comment by zeruniverse** [comment]
I think the group name is mistyped. It's very likely if the group name involves some special characters. You could try some groups with simple group name (e.g. only consists of numbers and English letters) and see whether the script works. I tried this script myself and I input exactly the group name in the txt file.
