### ISSUE TITLE
启动报list越界异常

### ISSUE THREAD

**Issue by shuhelloworld** [zeruniverse/QQRobot#35]
Fri, 11 Nov 2016 08:16:45  QQBot.py[line:293] INFO get g_mibao_css : 
Fri, 11 Nov 2016 08:16:45  QQBot.py[line:301] INFO [1] Get QRCode Picture Success.
Fri, 11 Nov 2016 08:16:45  QQBot.py[line:740] CRITICAL list index out of range

**Comment by shuhelloworld** [comment]
已经有图了，然后EXIT 1 异常退出了

**Comment by zeruniverse** [comment]
把这行的注释符号（#）删掉看看输出什么

https://github.com/zeruniverse/QQRobot/blob/master/QQBot.py#L306

**Comment by shuhelloworld** [comment]
nohup: ignoring input
  File "QQBot.py", line 306
    logging.info(html)
    ^
IndentationError: unexpected indent

**Comment by shuhelloworld** [comment]
没接触过py，这是语法的错误吗2333

**Comment by zeruniverse** [comment]
那一行的缩进问题，另外 调试的时候不能用nohup 不然你怎么看输出……

这种问题自己google一下啊……

**Comment by zeruniverse** [comment]
@shuhelloworld 查明TX协议更改导致错误，现已修复
