### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by tetsaicn** [zeruniverse/QQRobot#37]

**Comment by zeruniverse** [comment]
Umm 有好几个人开了issues想搞 ( #34 ) 但是最后都不了了之了。是这样 我本人不打算再搞android协议了 所以要搞的话需要有个人带头搞

**Comment by tetsaicn** [comment]
我给issues的人发了邮件，他们已回

**Comment by zeruniverse** [comment]
Also #27 and #13

**Comment by zeruniverse** [comment]
Good Luck!

**Comment by alanchenup** [comment]
怎么加入

**Comment by zeruniverse** [comment]
@tetsaicn FWD from TBoy

-----

[发布安卓QQ协议模块.zip](https://github.com/zeruniverse/QQRobot/files/862678/QQ.zip)

易语言模块，might be help.
