### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Yi-Lyu** [zeruniverse/QQRobot#38]
把第306行注释去掉，看到HTML返回为403内容。报错信息如下。

![image](https://cloud.githubusercontent.com/assets/1308846/25114459/6acbaeaa-2431-11e7-82d5-6efd0f635d98.png)

**Comment by Yi-Lyu** [comment]
的确有v.png验证码，但程序终止了，看到html信息是如上图。

**Comment by zeruniverse** [comment]
如果是vps的话 先试试用本地机器可不可以 vps的ip好像是不太行

**Comment by Yi-Lyu** [comment]
我这是在我的mac电脑上跑的。。。

**Comment by zeruniverse** [comment]
从这里看不出为什么你的403了。你可以尝试下先用你的浏览器登陆一下smartqq，再用程序。

**Comment by zeruniverse** [comment]
DUPLICATE #40

**Comment by zeruniverse** [comment]
@pangee 查明TX协议更改导致错误，现已修复
