### ISSUE TITLE
疑似协议已更新

### ISSUE THREAD

**Issue by violarulan** [zeruniverse/QQRobot#4]
一直提示登录失败

**Comment by Sunappnio** [comment]
没有出现这种情况， 只有在少数时候不回复（log里有但是对话中没有）
建议你看一下log

**Comment by hexsum** [comment]
今天也有人给我反馈类似的问题，checkVC的时候返回-1了 腾讯近期页面已经取消了账号密码的登录方式，只保留了二维码登录的方式，确实有做调整，但还不确定登录不成功具体是什么原因
