### ISSUE TITLE
出现CRITICAL list index out of range 无法正常使用

### ISSUE THREAD

**Issue by ztjryg4** [zeruniverse/QQRobot#40]
Sun, 07 May 2017 00:51:47  QQBot.py[line:279] CRITICAL 正在获取登陆页面
Sun, 07 May 2017 00:51:48  QQBot.py[line:283] CRITICAL 正在获取appid
Sun, 07 May 2017 00:51:48  QQBot.py[line:285] CRITICAL 正在获取login_sig
Sun, 07 May 2017 00:51:48  QQBot.py[line:287] INFO get sign :
Sun, 07 May 2017 00:51:48  QQBot.py[line:288] CRITICAL 正在获取pt_version
Sun, 07 May 2017 00:51:48  QQBot.py[line:290] INFO get g_pt_version : 10217
Sun, 07 May 2017 00:51:48  QQBot.py[line:291] CRITICAL 正在获取mibao_css
Sun, 07 May 2017 00:51:48  QQBot.py[line:293] INFO get g_mibao_css :
Sun, 07 May 2017 00:51:48  QQBot.py[line:301] INFO [1] Get QRCode Picture Success.
Sun, 07 May 2017 00:51:48  QQBot.py[line:743] CRITICAL list index out of range
以上为log内容

**Comment by zeruniverse** [comment]
出现这种错误基本就是网站回了个403。 可以尝试先用这台电脑的浏览器等一下smartqq 再重试

**Comment by ztjryg4** [comment]
谢谢！但是我在我的树莓派（基于Debian的系统）上使用Firefox登录了SmartQQ 重试后仍存在相同问题

**Comment by zeruniverse** [comment]
你试试在代码里面加一句，把返回的HTML输出来到log

**Comment by ztjryg4** [comment]
这是把HTML输出以后的log 确实返回了403 不清楚是什么原因
Mon, 08 May 2017 22:25:01  QQBot.py[line:279] CRITICAL 正在获取登陆页面
Mon, 08 May 2017 22:25:01  QQBot.py[line:283] CRITICAL 正在获取appid
Mon, 08 May 2017 22:25:01  QQBot.py[line:285] CRITICAL 正在获取login_sig
Mon, 08 May 2017 22:25:01  QQBot.py[line:287] INFO get sign :
Mon, 08 May 2017 22:25:01  QQBot.py[line:288] CRITICAL 正在获取pt_version
Mon, 08 May 2017 22:25:01  QQBot.py[line:290] INFO get g_pt_version : 10217
Mon, 08 May 2017 22:25:01  QQBot.py[line:291] CRITICAL 正在获取mibao_css
Mon, 08 May 2017 22:25:01  QQBot.py[line:293] INFO get g_mibao_css :
Mon, 08 May 2017 22:25:02  QQBot.py[line:301] INFO [1] Get QRCode Picture Success.
Mon, 08 May 2017 22:25:02  QQBot.py[line:306] INFO <html>
```
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Tencent Login Server</center>
</body>
</html>
```

Mon, 08 May 2017 22:25:02  QQBot.py[line:743] CRITICAL list index out of range

**Comment by zeruniverse** [comment]
403就没办法了 可能ip被tx封了之类的？ tx不说原因的

**Comment by ztjryg4** [comment]
好的 谢谢了！

**Comment by Phantomdft** [comment]
html = self.Get('https://ssl.ptlogin2.qq.com/ptqrlogin?webqq_type=10&remember_uin=1&login2qq=1&aid={0}&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-{1}&mibao_css={2}&t=undefined&g=1&js_type=0&js_ver={3}&login_sig={4}'.format(APPID, date_to_millis(datetime.datetime.utcnow()) - StarTime, MiBaoCss, JsVer, sign), self.initUrl)
这个url返回403 导致后面的ret列表越界

**Comment by ztjryg4** [comment]
噢噢谢谢 不好意思前两天没看见 有解决办法吗？

**Comment by zeruniverse** [comment]
嗯 我自己试了一下 确实有问题 可能TX协议改了。

**Comment by zeruniverse** [comment]
以前是偶尔403，现在一直403。 不过我现在自己基本已经不用qq了，所以可能修复进度会慢一点

**Comment by ztjryg4** [comment]
嗯明白了 非常感谢！

**Comment by zeruniverse** [comment]
@Phantomdft @ztjryg4 查明TX协议更改导致错误，现已修复
