### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by zhanggaoxuan** [zeruniverse/QQRobot#41]
[root@gov QQRobot]# nohup python2 QQBot.py >qbot.log&
[1] 23376
[root@gov QQRobot]# nohup: ignoring input and redirecting stderr to stdout

求解决

**Comment by zeruniverse** [comment]
1. 请下载最新版本 前天更新的
2.如果还有问题请附加log.log文件

**Comment by zhanggaoxuan** [comment]
我直接git `clone的。。
机器人能私聊回复，但是群聊的时候，就有问题。
就是你说的code0的问题，在挂机，慢慢等
 nohup: ignoring input and redirecting stderr to stdout
这个没问题么

**Comment by zeruniverse** [comment]
没问题 nohup就是这样的

所有记录都在log.log这个文件里 请查阅。 我估计群聊有问题是你群名没输对 群名要输在groupfollow.txt里

**Comment by zhanggaoxuan** [comment]
找到问题了，
用notepad++ 编辑，转为utd-8编码格式，有问题，会报错

Sun, 04 Jun 2017 14:42:45  QQBot.py[line:752] ERROR 无法找到群：﻿2016**新生群
为了保密，我在git把中间的字隐去了
用Notepad++改成utf-8无BOM编码格式就好了，
就会变成：
Sun, 04 Jun 2017 14:57:41  QQBot.py[line:750] INFO 关注:2016**新生群

但是目前私聊和群聊都不回复了。。。蛋疼

**Comment by zeruniverse** [comment]
要把原来的进程kill掉重新登录

如果还不行看看log是怎么回事

**Comment by zhanggaoxuan** [comment]
找到问题了，总自动断掉。
在线，但是不接收消息，查看log日志不新增内容。
难道我要执行cron任务？每分钟一次？有什么建议么？

**Comment by zeruniverse** [comment]
额 这个我没遇到过。 你可以看看是不是你这边哪里有问题？

**Comment by zhanggaoxuan** [comment]
每次执行任务都需要扫码- -
然后蛋疼了。。
不执行把，总断掉然后不接收消息了。。
是否可以考虑保存cookie之类或者其他的方式？

**Comment by zeruniverse** [comment]
暂时没有时间实现 抱歉
