### ISSUE TITLE
不能登录成功

### ISSUE THREAD

**Issue by akmumu** [zeruniverse/QQRobot#42]
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.4</center>
</body>
</html>

Fri, 07 Jul 2017 18:11:12  qqbot.py[line:372] CRITICAL 登录失败，正在重试
Fri, 07 Jul 2017 18:11:13  qqbot.py[line:367] INFO getvfwebqq html:  <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.4</center>
</body>
</html>

Fri, 07 Jul 2017 18:11:13  qqbot.py[line:372] CRITICAL 登录失败，正在重试
Fri, 07 Jul 2017 18:11:13  qqbot.py[line:784] CRITICAL local variable 'ret2' referenced before assignment

**Comment by zeruniverse** [comment]
先试试浏览器登录呢？？

**Comment by akmumu** [comment]
我这边浏览器登录一篇空白啊，难道smartQQ死了么

**Comment by zeruniverse** [comment]
那我就无能为力了
