### ISSUE TITLE
QQ安卓协议

### ISSUE THREAD

**Issue by wangkun19930608** [zeruniverse/QQRobot#46]
精易论坛有不少,只是很多是易语言的协议,而且时间还是比较早的.目前有一个酷Q的应用不错,看看能不能获取一些它以安卓身份登录的协议了.

**Comment by zeruniverse** [comment]
您好，我已經没有在开发这个项目了，但是如果您愿意开发android协议并成功实现的话，我会接受Pull request.

更多细节请见 #37
