### ISSUE TITLE
运行登录都成功，关键词回复时程序报错

### ISSUE THREAD

**Issue by peaceanddemocracy** [zeruniverse/QQRobot#47]
![qq 20180105201331](https://user-images.githubusercontent.com/10943213/34608778-edf3f980-f254-11e7-8315-f84ec6da50e4.png)

**Comment by zeruniverse** [comment]
可能加载群列表没成功，多试几次

**Comment by peaceanddemocracy** [comment]
尝试多次依旧无效

**Comment by peaceanddemocracy** [comment]
也已经更换环境，是不是缺少运行环境什么的

**Comment by zeruniverse** [comment]
你环境没缺

这个需要debug一下 你改下代码把那个dict打出来 看看报错的gid有没有在里面

**Comment by peaceanddemocracy** [comment]
py的代码我不太会改，能否指导一二

**Comment by zeruniverse** [comment]
这个一时半会儿讲不清楚，你自己学习下python吧
