### ISSUE TITLE
一起分析 Android QQ协议？

### ISSUE THREAD

**Issue by sionnx** [zeruniverse/QQRobot#51]
学习Android 逆向一段时间了，最近开始搞QQ逆向，一起交流一起分析？没找到你邮箱 只能在这联系你。

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zeruniverse** [comment]
感觉这个年代已经没人用QQ了

**Comment by campanulamediuml** [comment]
也不会，qq其实很多人用，都是年轻人，不过我看了一下，现在有个很成熟的qchttp协议了，可以照着实现就行了

Jeffery (Zeyu) Zhao ***@***.***> 于2019年9月18日周三 00:31写道：
