### ISSUE TITLE
1473162392@qq.com

### ISSUE THREAD

**Issue by talway** [zeruniverse/QQRobot#8]
能增加群聊天记录吗?发布成网站出去,用于保存聊天内容,有些聊天内容比较有价值

**Comment by zeruniverse** [comment]
这个不难实现，你网站上弄个接口，然后把机器人收到的和要发的都post过去。总共就不到10行代码

**Comment by talway** [comment]
谢谢回复，能否你做出来一下，我想关闭群聊，只是记录聊天内容；我不会代码，麻烦你写，谢谢了！

**Comment by hexsum** [comment]
不会代码，写了你也无法使用唉，需求描述太粗略了

**Comment by zeruniverse** [comment]
这……你不会还想让我写个网站吧
