### ISSUE TITLE
求助：聊天机器人上传到VPS或GAE/SAE的方法

### ISSUE THREAD

**Issue by ghost** [zeruniverse/QQRobot#9]
开发者您好，首先感谢您的辛苦付出！
您在项目描述中写到支持VPS的挂机，是否意味着使用者可以把代码放到免费VPS的VPS甚至是Google App Engine上？
原本是做嵌入式的，又是刚刚接触phython，不了解网络协议实在非常抱歉。所以恳切希望您能提供一些初浅的例程参考
谢谢您

**Comment by zeruniverse** [comment]
Any machine/platform running python2.7 will do.

Thanks!

**Comment by zeruniverse** [comment]
You don't need to know any Python to run this program unless you want to further develop it. Just download it and upload to your server, put your configs according to README file then you are good to go. I don't know what do you mean by example program… my program is just an executable one, not a library…

**Comment by ghost** [comment]
Thanks for reply.
According to your description, can I consider that I can upload these files to any VPS or Paas directly and run?
p.s.我是大陆这边的……如果是我的措辞不当劳您费心翻译成外文我表示非常抱歉

**Comment by zeruniverse** [comment]
Yes, just try it out
